VPATH =\
	$(SRC_DIR_GENERATED)IO\
	$(SRC_DIR_GENERATED)apply_face_bc_op\
	$(SRC_DIR_GENERATED)block\
	$(SRC_DIR_GENERATED)block_field\
	$(SRC_DIR_GENERATED)boundary_conditions\
	$(SRC_DIR_GENERATED)data_location\
	$(SRC_DIR_GENERATED)dir_tree\
	$(SRC_DIR_GENERATED)fft_solver\
	$(SRC_DIR_GENERATED)fields\
	$(SRC_DIR_GENERATED)governing_equations\
	$(SRC_DIR_GENERATED)grid\
	$(SRC_DIR_GENERATED)grid_field\
	$(SRC_DIR_GENERATED)mesh\
	$(SRC_DIR_GENERATED)mesh_domain\
	$(SRC_DIR_GENERATED)mesh_params\
	$(SRC_DIR_GENERATED)moons\
	$(SRC_DIR_GENERATED)pcg\
	$(SRC_DIR_GENERATED)physical_domain\
	$(SRC_DIR_GENERATED)precision\
	$(SRC_DIR_GENERATED)probe\
	$(SRC_DIR_GENERATED)procedure_array\
	$(SRC_DIR_GENERATED)sim_params\
	$(SRC_DIR_GENERATED)stitches\
	$(SRC_DIR_GENERATED)stop_clock\
	$(SRC_DIR_GENERATED)string\
	$(SRC_DIR_GENERATED)sub_domain\
	$(SRC_DIR_GENERATED)time_statistics\
	$(SRC_DIR_GENERATED)var_set\

SRCS_F=\
	$(SRC_DIR_GENERATED)precision$(PS)current_precision.f90\
	$(SRC_DIR_GENERATED)IO$(PS)inquire_funcs.f90\
	$(SRC_DIR_GENERATED)IO$(PS)IO_check.f90\
	$(SRC_DIR_GENERATED)IO$(PS)IO_tools.f90\
	$(SRC_DIR_GENERATED)string$(PS)string.f90\
	$(SRC_DIR_GENERATED)string$(PS)string_aux.f90\
	$(SRC_DIR_GENERATED)dir_tree$(PS)path.f90\
	$(SRC_DIR_GENERATED)dir_tree$(PS)dir_group.f90\
	$(SRC_DIR_GENERATED)dir_tree$(PS)dir_tree.f90\
	$(SRC_DIR_GENERATED)stitches$(PS)stitch.f90\
	$(SRC_DIR_GENERATED)stitches$(PS)stitch_face.f90\
	$(SRC_DIR_GENERATED)probe$(PS)probe.f90\
	$(SRC_DIR_GENERATED)mesh_params$(PS)mesh_quality_params.f90\
	$(SRC_DIR_GENERATED)mesh_params$(PS)segment.f90\
	$(SRC_DIR_GENERATED)mesh_params$(PS)mesh_params.f90\
	$(SRC_DIR_GENERATED)grid$(PS)array.f90\
	$(SRC_DIR_GENERATED)grid$(PS)sparse.f90\
	$(SRC_DIR_GENERATED)grid$(PS)coordinates.f90\
	$(SRC_DIR_GENERATED)grid$(PS)grid.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)rk_params.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)solver_settings.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)matrix_free_params.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)time_marching_params.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)iter_solver_params.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)export_line.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)export_lines.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)export_plane.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)export_planes.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)export_field.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)var.f90\
	$(SRC_DIR_GENERATED)var_set$(PS)var_set.f90\
	$(SRC_DIR_GENERATED)stop_clock$(PS)unit_conversion.f90\
	$(SRC_DIR_GENERATED)stop_clock$(PS)clock.f90\
	$(SRC_DIR_GENERATED)stop_clock$(PS)stop_clock.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)stats_period.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)time_statistics_params.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)mirror_props.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)export_logicals.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)geometry_props.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)equation_term.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)energy_terms.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)momentum_terms.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)induction_terms.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)export_frequency_params.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)export_frequency.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)flow_control_logicals.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)sim_config_params.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)dimensionless_params.f90\
	$(SRC_DIR_GENERATED)sim_params$(PS)sim_params.f90\
	$(SRC_DIR_GENERATED)grid_field$(PS)grid_field.f90\
	$(SRC_DIR_GENERATED)data_location$(PS)data_location.f90\
	$(SRC_DIR_GENERATED)sub_domain$(PS)overlap.f90\
	$(SRC_DIR_GENERATED)sub_domain$(PS)sub_domain.f90\
	$(SRC_DIR_GENERATED)sub_domain$(PS)index_2d.f90\
	$(SRC_DIR_GENERATED)sub_domain$(PS)face_sd.f90\
	$(SRC_DIR_GENERATED)physical_domain$(PS)physical_sub_domain.f90\
	$(SRC_DIR_GENERATED)physical_domain$(PS)physical_domain.f90\
	$(SRC_DIR_GENERATED)apply_face_bc_op$(PS)apply_face_bc_op.f90\
	$(SRC_DIR_GENERATED)apply_face_bc_op$(PS)plane_op.f90\
	$(SRC_DIR_GENERATED)procedure_array$(PS)single_procedure.f90\
	$(SRC_DIR_GENERATED)procedure_array$(PS)single_procedure_plane_op.f90\
	$(SRC_DIR_GENERATED)procedure_array$(PS)procedure_array.f90\
	$(SRC_DIR_GENERATED)procedure_array$(PS)procedure_array_plane_op.f90\
	$(SRC_DIR_GENERATED)boundary_conditions$(PS)bc_logicals.f90\
	$(SRC_DIR_GENERATED)boundary_conditions$(PS)bctype.f90\
	$(SRC_DIR_GENERATED)boundary_conditions$(PS)single_boundary.f90\
	$(SRC_DIR_GENERATED)boundary_conditions$(PS)boundary.f90\
	$(SRC_DIR_GENERATED)boundary_conditions$(PS)boundary_conditions.f90\
	$(SRC_DIR_GENERATED)block$(PS)block.f90\
	$(SRC_DIR_GENERATED)block_field$(PS)block_field.f90\
	$(SRC_DIR_GENERATED)mesh$(PS)simple_int_tensor.f90\
	$(SRC_DIR_GENERATED)mesh$(PS)mesh_props.f90\
	$(SRC_DIR_GENERATED)mesh$(PS)mesh.f90\
	$(SRC_DIR_GENERATED)mesh$(PS)mesh_block.f90\
	$(SRC_DIR_GENERATED)fields$(PS)sf.f90\
	$(SRC_DIR_GENERATED)fields$(PS)vf.f90\
	$(SRC_DIR_GENERATED)fields$(PS)tf.f90\
	$(SRC_DIR_GENERATED)mesh_domain$(PS)mesh_domain.f90\
	$(SRC_DIR_GENERATED)time_statistics$(PS)time_statistics_sf.f90\
	$(SRC_DIR_GENERATED)time_statistics$(PS)time_statistics_vf.f90\
	$(SRC_DIR_GENERATED)pcg$(PS)preconditioners.f90\
	$(SRC_DIR_GENERATED)pcg$(PS)matrix_free_operators.f90\
	$(SRC_DIR_GENERATED)pcg$(PS)norms.f90\
	$(SRC_DIR_GENERATED)pcg$(PS)pcg_solver_sf.f90\
	$(SRC_DIR_GENERATED)pcg$(PS)pcg_solver_vf.f90\
	$(SRC_DIR_GENERATED)fft_solver$(PS)fft_solver_sf.f90\
	$(SRC_DIR_GENERATED)governing_equations$(PS)momentum.f90\
	$(SRC_DIR_GENERATED)governing_equations$(PS)induction.f90\
	$(SRC_DIR_GENERATED)governing_equations$(PS)energy.f90\
	$(SRC_DIR_GENERATED)governing_equations$(PS)density.f90\
	$(SRC_DIR_GENERATED)moons$(PS)kill_switch.f90\
	$(SRC_DIR_GENERATED)moons$(PS)step.f90\
	$(SRC_DIR_GENERATED)moons$(PS)export_now.f90\
	$(SRC_DIR_GENERATED)moons$(PS)refine_mesh.f90\
	$(SRC_DIR_GENERATED)moons$(PS)export_safe.f90\
	$(SRC_DIR_GENERATED)moons$(PS)restart_file.f90\
	$(SRC_DIR_GENERATED)moons$(PS)moons.f90\
