REM gfortran -fopenmp -g -Wall -Wextra -pedantic -fimplicit-none -fbacktrace -cpp -fcheck=all -Wuninitialized^

SET TAR_DIR=C:\\Users\\charl\\Documents\\MOONS\\MOONS5

rem relative path works but full path does not work
rem no matter what separater is used, with or without quotes.

rem SET SRC_DIR=code
SET SRC_DIR=C:\\Users\\charl\\Documents\\GitHub\\MOONS\\code\\

gfortran -fopenmp -g -fimplicit-none -cpp ^
 %SRC_DIR%\\globals\\current_precision.f90^
 %SRC_DIR%\\string\\string.f90^
 %SRC_DIR%\\math\\isnan.f90^
 %SRC_DIR%\\IO\\IO_tools.f90^
 %SRC_DIR%\\IO\\exp_Tecplot_Zone.f90^
 %SRC_DIR%\\IO\\exp_Tecplot_Header.f90^
 %SRC_DIR%\\IO\\IO_auxiliary.f90^
 %SRC_DIR%\\directory\\draw_DT.f90^
 %SRC_DIR%\\directory\\dir_tree.f90^
 %SRC_DIR%\\sparse\\array.f90^
 %SRC_DIR%\\sparse\\sparse.f90^
 %SRC_DIR%\\sparse\\triDiag.f90^
 %SRC_DIR%\\BCs\\face_edge_corner_indexing.f90^
 %SRC_DIR%\\stitches\\stitch.f90^
 %SRC_DIR%\\stitches\\stitch_face.f90^
 %SRC_DIR%\\stitches\\stitch_edge.f90^
 %SRC_DIR%\\stitches\\stitch_corner.f90^
 %SRC_DIR%\\coordinates\\coordinates.f90^
 %SRC_DIR%\\grid\\grid.f90^
 %SRC_DIR%\\grid\\grid_distribution_funcs.f90^
 %SRC_DIR%\\grid\\grid_genHelper.f90^
 %SRC_DIR%\\grid\\grid_stretchParamMatch.f90^
 %SRC_DIR%\\grid\\grid_init.f90^
 %SRC_DIR%\\grid\\grid_extend.f90^
 %SRC_DIR%\\grid\\grid_connect.f90^
 %SRC_DIR%\\grid\\grid_generate.f90^
 %SRC_DIR%\\BCs\\bctype.f90^
 %SRC_DIR%\\BCs\\corner.f90^
 %SRC_DIR%\\BCs\\edge.f90^
 %SRC_DIR%\\BCs\\face.f90^
 %SRC_DIR%\\BCs\\BCs.f90^
 %SRC_DIR%\\fields\\RF.f90^
 %SRC_DIR%\\mesh\\mesh.f90^
 %SRC_DIR%\\user\\simParams.f90^
 %SRC_DIR%\\grid\\subdomain.f90^
 %SRC_DIR%\\grid\\domain.f90^
 %SRC_DIR%\\mesh\\mesh_simple_geometries.f90^
 %SRC_DIR%\\mesh\\mesh_complex_geometries.f90^
 %SRC_DIR%\\mesh\\mesh_generate.f90^
 %SRC_DIR%\\fields\\SF.f90^
 %SRC_DIR%\\fields\\VF.f90^
 %SRC_DIR%\\fields\\TF.f90^
 %SRC_DIR%\\fields\\index_mapping.f90^
 %SRC_DIR%\\IO\\export_raw.f90^
 %SRC_DIR%\\IO\\export_g.f90^
 %SRC_DIR%\\IO\\export_SF.f90^
 %SRC_DIR%\\IO\\export_VF.f90^
 %SRC_DIR%\\IO\\import_raw.f90^
 %SRC_DIR%\\IO\\import_g.f90^
 %SRC_DIR%\\IO\\import_SF.f90^
 %SRC_DIR%\\IO\\import_VF.f90^
 %SRC_DIR%\\IO\\IO_SF.f90^
 %SRC_DIR%\\IO\\IO_VF.f90^
 %SRC_DIR%\\version\\version.f90^
 %SRC_DIR%\\clock\\clock.f90^
 %SRC_DIR%\\clock\\stop_clock.f90^
 %SRC_DIR%\\ops\\ops_norms.f90^
 %SRC_DIR%\\norms\\norms.f90^
 %SRC_DIR%\\stitches\\apply_stitches_faces.f90^
 %SRC_DIR%\\stitches\\apply_stitches_edges.f90^
 %SRC_DIR%\\stitches\\apply_stitches_corners.f90^
 %SRC_DIR%\\stitches\\apply_stitches.f90^
 %SRC_DIR%\\ops\\ops_fft.f90^
 %SRC_DIR%\\ops\\ops_dct.f90^
 %SRC_DIR%\\ops\\ops_idct.f90^
 %SRC_DIR%\\stencils\\stencils.f90^
 %SRC_DIR%\\ops\\ops_del.f90^
 %SRC_DIR%\\ops\\ops_embedExtract.f90^
 %SRC_DIR%\\ops\\ops_BEM.f90^
 %SRC_DIR%\\BCs\\check_BCs.f90^
 %SRC_DIR%\\BCs\\apply_BCs_faces.f90^
 %SRC_DIR%\\BCs\\apply_BCs_faces_implicit.f90^
 %SRC_DIR%\\BCs\\apply_BCs_edges_implicit.f90^
 %SRC_DIR%\\BCs\\apply_BCs_edges.f90^
 %SRC_DIR%\\BCs\\apply_BCs_corners.f90^
 %SRC_DIR%\\BCs\\apply_BCs.f90^
 %SRC_DIR%\\BCs\\apply_BCs_implicit.f90^
 %SRC_DIR%\\ops\\ops_interp.f90^
 %SRC_DIR%\\ops\\ops_aux.f90^
 %SRC_DIR%\\ops\\ops_discrete.f90^
 %SRC_DIR%\\ops\\ops_advect.f90^
 %SRC_DIR%\\IO\\export_raw_processed.f90^
 %SRC_DIR%\\probes\\probe_transient.f90^
 %SRC_DIR%\\probes\\probe_base.f90^
 %SRC_DIR%\\probes\\probe_derived.f90^
 %SRC_DIR%\\solvers\\matrix_free_params.f90^
 %SRC_DIR%\\solvers\\matrix_free_operators.f90^
 %SRC_DIR%\\solvers\\preconditioners.f90^
 %SRC_DIR%\\solvers\\AB2.f90^
 %SRC_DIR%\\solvers\\compute_energy.f90^
 %SRC_DIR%\\sparse\\matrix.f90^
 %SRC_DIR%\\solvers\\FFT\\FFT_poisson.f90^
 %SRC_DIR%\\solvers\\Jacobi\\Jacobi_solver.f90^
 %SRC_DIR%\\solvers\\Jacobi\\Jacobi.f90^
 %SRC_DIR%\\solvers\\GS\\GS_poisson.f90^
 %SRC_DIR%\\solvers\\SOR\\SOR.f90^
 %SRC_DIR%\\solvers\\PSE\\PSE_solver.f90^
 %SRC_DIR%\\solvers\\PSE\\PSE.f90^
 %SRC_DIR%\\solvers\\PCG\\PCG_aux.f90^
 %SRC_DIR%\\solvers\\PCG\\PCG_solver.f90^
 %SRC_DIR%\\solvers\\PCG\\PCG.f90^
 %SRC_DIR%\\solvers\\energy\\init_TBCs.f90^
 %SRC_DIR%\\solvers\\energy\\init_Tfield.f90^
 %SRC_DIR%\\solvers\\energy\\init_K.f90^
 %SRC_DIR%\\solvers\\energy\\energy_aux.f90^
 %SRC_DIR%\\solvers\\energy\\energy_solver.f90^
 %SRC_DIR%\\solvers\\energy\\energy.f90^
 %SRC_DIR%\\solvers\\momentum\\profile_funcs.f90^
 %SRC_DIR%\\solvers\\momentum\\init_UBCs.f90^
 %SRC_DIR%\\solvers\\momentum\\init_PBCs.f90^
 %SRC_DIR%\\solvers\\momentum\\init_Ufield.f90^
 %SRC_DIR%\\solvers\\momentum\\init_Pfield.f90^
 %SRC_DIR%\\solvers\\momentum\\E_K_budget_terms.f90^
 %SRC_DIR%\\solvers\\momentum\\E_K_budget.f90^
 %SRC_DIR%\\solvers\\momentum\\momentum_aux.f90^
 %SRC_DIR%\\solvers\\momentum\\momentum_solver.f90^
 %SRC_DIR%\\solvers\\momentum\\momentum.f90^
 %SRC_DIR%\\solvers\\induction\\E_M_budget_terms.f90^
 %SRC_DIR%\\solvers\\induction\\E_M_budget.f90^
 %SRC_DIR%\\solvers\\induction\\init_phiBCs.f90^
 %SRC_DIR%\\solvers\\induction\\init_BBCs.f90^
 %SRC_DIR%\\solvers\\induction\\init_Bfield.f90^
 %SRC_DIR%\\solvers\\induction\\init_Sigma.f90^
 %SRC_DIR%\\solvers\\induction\\induction_aux.f90^
 %SRC_DIR%\\solvers\\induction\\induction_solver.f90^
 %SRC_DIR%\\solvers\\induction\\induction.f90^
 %SRC_DIR%\\solvers\\MHDSolver.f90^
 %SRC_DIR%\\user\\inputFile.f90^
 %SRC_DIR%\\user\\MOONS.f90^
 parametricStudy.f90^
 -o main.exe
del *.mod