gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/precision/current_precision.o   ../source/precision/current_precision.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/IO/inquire_funcs.o   ../source/IO/inquire_funcs.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/IO/IO_check.o   ../source/IO/IO_check.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/IO/IO_tools.o   ../source/IO/IO_tools.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/string/string.o   ../source/string/string.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/string/string_aux.o   ../source/string/string_aux.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch_face.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch_face.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin"  -o output C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/main_dummy.f90 ../source/precision/current_precision.o   ../source/IO/inquire_funcs.o   ../source/IO/IO_check.o   ../source/IO/IO_tools.o   ../source/string/string.o   ../source/string/string_aux.o   C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch_face.o  
 output.exe
 cd generated_code
 del *.o
 cd ..