gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/precision/current_precision.o   ../source/precision/current_precision.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/IO/inquire_funcs.o   ../source/IO/inquire_funcs.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/IO/IO_check.o   ../source/IO/IO_check.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/IO/IO_tools.o   ../source/IO/IO_tools.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/string/string.o   ../source/string/string.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/string/string_aux.o   ../source/string/string_aux.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch_face.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch_face.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/path.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/path.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/dir_group.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/dir_group.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/dir_tree.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/dir_tree.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/probe/probe.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/probe/probe.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/mesh_quality_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/mesh_quality_params.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/segment.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/segment.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/mesh_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/mesh_params.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/array.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/array.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/sparse.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/sparse.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/coordinates.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/coordinates.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/grid.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/grid.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/RK_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/RK_params.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/solver_settings.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/solver_settings.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/matrix_free_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/matrix_free_params.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/time_marching_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/time_marching_params.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/iter_solver_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/iter_solver_params.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_line.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_line.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_lines.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_lines.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_plane.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_plane.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_planes.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_planes.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_field.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_field.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/var.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/var.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/var_set.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/var_set.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin"  -o output C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/main_dummy.f90 ../source/precision/current_precision.o   ../source/IO/inquire_funcs.o   ../source/IO/IO_check.o   ../source/IO/IO_tools.o   ../source/string/string.o   ../source/string/string_aux.o   C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/stitches/stitch_face.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/path.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/dir_group.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/dir_tree/dir_tree.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/probe/probe.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/mesh_quality_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/segment.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/mesh_params/mesh_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/array.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/sparse.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/coordinates.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/grid/grid.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/RK_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/solver_settings.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/matrix_free_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/time_marching_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/iter_solver_params.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_line.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_lines.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_plane.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_planes.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/export_field.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/var.o  C:\Users\Charlie\Documents\GitHub\MOONS/code/generated_code/var_set/var_set.o  
 output.exe
 cd generated_code
 del *.o
 cd ..