VPATH +=\
	$(TARGET_DIR)\
	$(SRC_DIR)$(PS)apply_face_BC_op\
	$(SRC_DIR)$(PS)block\
	$(SRC_DIR)$(PS)block_field\
	$(SRC_DIR)$(PS)boundary_conditions\
	$(SRC_DIR)$(PS)BCs\
	$(SRC_DIR)$(PS)BCs$(PS)apply\
	$(SRC_DIR)$(PS)BCs$(PS)base\
	$(SRC_DIR)$(PS)BCs$(PS)direct\
	$(SRC_DIR)$(PS)BCs$(PS)implicit\
	$(SRC_DIR)$(PS)stop_clock\
	$(SRC_DIR)$(PS)convergence_rate\
	$(SRC_DIR)$(PS)coordinates\
	$(SRC_DIR)$(PS)dir_tree\
	$(SRC_DIR)$(PS)domain\
	$(SRC_DIR)$(PS)governing_equations\
	$(SRC_DIR)$(PS)mesh_params\
	$(SRC_DIR)$(PS)mesh_domain\
	$(SRC_DIR)$(PS)grid_field\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_2D\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_3D\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_global\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_export_import\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_embed_extract\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_MG\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_interp\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_symmetry\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_CFL_number\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_Fourier_number\
	$(SRC_DIR)$(PS)grid_field$(PS)GF_Robin_BC_coeff\
	$(SRC_DIR)$(PS)fields\
	$(SRC_DIR)$(PS)fields$(PS)default\
	$(SRC_DIR)$(PS)fields$(PS)default$(PS)TF\
	$(SRC_DIR)$(PS)globals\
	$(SRC_DIR)$(PS)grid\
	$(SRC_DIR)$(PS)grid_field\
	$(SRC_DIR)$(PS)IO\
	$(SRC_DIR)$(PS)lib\
	$(SRC_DIR)$(PS)math\
	$(SRC_DIR)$(PS)mesh\
	$(SRC_DIR)$(PS)MOONS\
	$(SRC_DIR)$(PS)norms\
	$(SRC_DIR)$(PS)ops\
	$(SRC_DIR)$(PS)PCG\
	$(SRC_DIR)$(PS)physical_domain\
	$(SRC_DIR)$(PS)procedure_array\
	$(SRC_DIR)$(PS)probe\
	$(SRC_DIR)$(PS)sim_params\
	$(SRC_DIR)$(PS)sub_domain\
	$(SRC_DIR)$(PS)var_set\
	$(SRC_DIR)$(PS)solvers\
	$(SRC_DIR)$(PS)solvers$(PS)density\
	$(SRC_DIR)$(PS)solvers$(PS)energy\
	$(SRC_DIR)$(PS)solvers$(PS)FFT\
	$(SRC_DIR)$(PS)solvers$(PS)GS\
	$(SRC_DIR)$(PS)solvers$(PS)induction\
	$(SRC_DIR)$(PS)solvers$(PS)Jacobi\
	$(SRC_DIR)$(PS)solvers$(PS)MG\
	$(SRC_DIR)$(PS)solvers$(PS)momentum\
	$(SRC_DIR)$(PS)solvers$(PS)PCG\
	$(SRC_DIR)$(PS)solvers$(PS)PSE\
	$(SRC_DIR)$(PS)solvers$(PS)SOR\
	$(SRC_DIR)$(PS)solvers$(PS)preconditioners\
	$(SRC_DIR)$(PS)sparse\
	$(SRC_DIR)$(PS)stencils\
	$(SRC_DIR)$(PS)table\
	$(SRC_DIR)$(PS)time_statistics\
	$(SRC_DIR)$(PS)matrix_vis\
	$(SRC_DIR)$(PS)version
